### PR TITLE
Small refactoring

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️

Replaced `{visibility-modifier}::{property-name}` to `{visibility-modifier} ${property-name}` (like a php-style): e.g. `public::username` -> `public $username`
Wrapped raw closure's code with object: `"fn () => 1"` => `{"Closure#1":"fn () => 1"}`

### CODE REVIEW

**Comment by yiiliveext** [comment]
Make top-level objects map keys with object ids, like 
```json
"My\Class#44": {
    "public::name": "MyClassName" 
} 
``

**Comment by xepozz** [comment]
It's already it is.
image

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Comment by yiiliveext** [comment]
> It's already it is.
> image

It doesn't. You have an integer indexed array instead of the object map.

**Pull request merged**
